package com.wadpam.spara.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DTicket.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-12-30T10:42:27.179+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DTicketDaoBean 
	extends GeneratedDTicketDaoImpl
{

  @Inject
  public DTicketDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
